language: python
python:
- 3.8
install:
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: kTvjFzTRjqA9LmuMG6uVjF7DnwBVyL9h1H7KQPhfOAauV076LJ5Kvp+QG2kC5m8AJVEJKOSFKsFAwtkQgEpQeIrjk5y+GtFdK7Ag2HK0kOjf/txLveVbWAROOfpN2lHUUO5xNi0C66ZN2G6RH7FYF6/98OJouVZ+safXoivXzQMr1Ey1pnllbgu179X7KuWQ4svLKfQnd8B24gok+SALNHtTOr90ryiFSa9Es9X1hrU9U5T6bpRkSFBnc4qGmPPXwYKdmbhdRf/c3wlmpmyxMntxPQ8n9YISxftUWEBZoy+tIE7PCPzo9Ou6mNq3mKFxh8lnnUGxlCxiG4sftv9K6FCBsGL0IhKlazQpQv/92iVQL/M6XVsVHEPdacH0Eo7zB3Zd+0H756NMiHWkLe0G+mZeLVohBjcsZztJvD6uiZfK6YYlPVfLP+Td/Y4GeqDYboTgH2v/8z4iZSvzuVcKq2UbiLs+JBMPqXIX+oBO046Y6a7ZcA/eNoczaqIMgEfMm9zRLYo00p/Fb5yEv10D6jQiLYjHExHtmeshhIKvb3pmvHnyMBSkXXBCL4g0Ay+Pj/ImECfmuinM4a3hro+gnGimmWgSV+2EaRzCad7JKyN+YvsTBDkLhvX+o4fC750sHeO1EsuTKpui8mqSQ9X+F1xJVTMqfAPGl8VcvW/oDQQ=
  on:
    branch: main
    repo: zhengp0/spmat
    tags: true
