language: python
python:
- 3.8
install:
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: JkQRj1WqzcCMCf14NTwzq1CB3mKAUlZY0zXiZEib2S9+OK0HF2kKW70LZRaaDFW/+g6dUeCYrACBTSEn2KbE8tiK+UgIpN9Hnt1r/+TcNAhssuf48IDmX7ZczUW/CuQTIMilKL7vHqnTnDw6usRMIiZ7CNOPa6qZpXsZTP8B5zCsRFC7HA6ZxsLzdorNRV6WIXGLygAd7R187aUPfl+I8/Yyy2CQf3NlvCT1vztUiy1rxAxPqvxQZJEqu1gHEOU2T+Ym7uzGqx6XGS6JtfgLcey9sGYEpJX1MS8nMfbbjYcScgQ4cHYjhs2kprZrr/4oD/jxH/yVNHyT8O38r122vG9lH0Lr4MM8Hlrxvvy+hRU++Ns2X2IEBArCRyfsfRwKE5oUig6++7SuF+bGlmDyBoAv0ioLQD6NIZNk8QTeddvLMT5LAv03EcNLglNO6yKm+WweCg7fAB6WKmaQlTx9OGa4BAQzBmXQWJbFqJ5bA7xrv1BnBo4c0Wkbkfbx3EasuqhqFbiSZjRZj3hCqpN0Dfun4gma0sUejB4i7WZuu6ZPkzCG5GZXlRp9Ttv3DJYNOwFxopnpKlbZz15pQXau5EOcV4tUXLKt8/KarR+nCa3FDXxK9POcpa8sTkQxhEDd6z3ZMltJ8qAkiBFHJ63L5mG7vH5F3FrdYy3dDeJWDKM=
  on:
    branch: main
    repo: zhengp0/spmat
    tags: true
