name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.1.4
        with: { output-dir: wheelhouse }
        env:
          CIBW_SKIP: "*-win32"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest -v {project}/tests"
          CIBW_BEFORE_BUILD: "pip install --upgrade pip setuptools wheel"

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
          ls -la dist/
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  collect_artifacts:
    name: Collect all artifacts
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Verify all artifacts
        run: |
          echo "Wheels:" && ls -la dist/*.whl || true
          echo "Sdists:" && ls -la dist/*.tar.gz || true
          echo "All:" && ls -la dist/

      - name: Upload combined artifact (all-distributions)
        uses: actions/upload-artifact@v4
        with:
          name: all-distributions
          path: dist/*
