# =============================================================================
# GitHub Actions Workflow: Build Wheels and Source Distribution
# =============================================================================

name: build

on:
  push:
  pull_request:
  # Manual trigger for testing builds
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ========================================================================
  # Build wheels (Linux, Windows, macOS)
  # ========================================================================
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.1.4
        with:
          output-dir: wheelhouse
        env:
          # Skip Windows 32-bit
          CIBW_SKIP: "*-win32"

          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest -q {project}/tests"
          CIBW_BEFORE_BUILD: "pip install --upgrade pip setuptools wheel"

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 30

  # ========================================================================
  # Build source distribution (sdist)
  # ========================================================================
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build source distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
          ls -la dist/

      - name: Upload source distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 30

  # ========================================================================
  # Collect all artifacts for potential deployment
  # ========================================================================
  collect_artifacts:
    name: Collect all artifacts
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Download source distribution
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Verify all artifacts
        run: |
          echo "Wheels found:" && ls -la dist/*.whl || true
          echo "Source dists found:" && ls -la dist/*.tar.gz || true
          echo "Total artifacts:" && ls -la dist/

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-distributions
          path: dist/*
          retention-days: 30
