# =============================================================================
# GitHub Actions Workflow: Build Wheels and Source Distribution
# =============================================================================

name: build

on:
  push:
  pull_request:
  # Manual trigger for testing builds
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            cibw_archs: "x86_64"
          # Linux ARM64
          - os: ubuntu-24.04-arm
            cibw_archs: "aarch64"
          # Windows x86_64
          - os: windows-latest
            cibw_archs_windows: "AMD64"
          # Windows ARM64 (only build py312/py313 here)
          - os: windows-11-arm
            cibw_archs_windows: "ARM64"
            cibw_build: "cp312-win_arm64 cp313-win_arm64"
            cibw_env_windows: "PIP_PREFER_BINARY=1 PIP_ONLY_BINARY=numpy,scipy"
          # macOS Intel
          - os: macos-13
          # macOS Apple Silicon
          - os: macos-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.1.4
        with:
          output-dir: wheelhouse
        env:
          # Per-OS arch/build selectors (empty ones are ignored)
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_archs_windows }}
          CIBW_BUILD: ${{ matrix.cibw_build }}
          # Only needed on Windows ARM to force binaries for numpy/scipy
          CIBW_ENVIRONMENT_WINDOWS: ${{ matrix.cibw_env_windows }}
          # Global settings
          CIBW_SKIP: "*-win32"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest -v {project}/tests"
          CIBW_BEFORE_BUILD: "pip install --upgrade pip setuptools wheel"


      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 30

  # ========================================================================
  # Build source distribution (sdist)
  # ========================================================================
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build source distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
          ls -la dist/

      - name: Upload source distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 30

  # ========================================================================
  # Collect all artifacts for potential deployment
  # ========================================================================
  collect_artifacts:
    name: Collect all artifacts
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Download source distribution
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Verify all artifacts
        run: |
          echo "Wheels found:" && ls -la dist/*.whl || true
          echo "Source dists found:" && ls -la dist/*.tar.gz || true
          echo "Total artifacts:" && ls -la dist/

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-distributions
          path: dist/*
          retention-days: 30
