# =============================================================================
# GitHub Actions Workflow: Deploy to PyPI
# =============================================================================

name: deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  # ========================================================================
  # Wait for build workflow to complete successfully
  # ========================================================================
  wait_for_build:
    name: Wait for build workflow
    runs-on: ubuntu-latest
    outputs:
      build_run_id: ${{ steps.get-build.outputs.run_id }}
    steps:
      - name: Get build workflow run ID
        id: get-build
        run: |
          # Get the most recent successful build workflow run for this commit
          BUILD_RUN=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.name == "build" and .head_sha == "${{ github.sha }}" and .conclusion == "success") | .id' \
            --paginate | head -1)
          
          if [ -z "$BUILD_RUN" ]; then
            echo "No successful build workflow found for commit ${{ github.sha }}"
            exit 1
          fi
          
          echo "run_id=$BUILD_RUN" >> $GITHUB_OUTPUT
          echo "Found successful build workflow run: $BUILD_RUN"

  # ========================================================================
  # Download built artifacts and publish to PyPI
  # ========================================================================
  upload_pypi:
    name: Publish to PyPI
    needs: [wait_for_build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all distributions from build workflow
        uses: actions/download-artifact@v4
        with:
          name: all-distributions
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.wait_for_build.outputs.build_run_id }}

      - name: Verify artifacts
        run: |
          echo "Wheels found:" && ls -la dist/*.whl || true
          echo "Source dists found:" && ls -la dist/*.tar.gz || true
          echo "Total artifacts:" && ls -la dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true