name: test_deploy

on:
  workflow_call:
    inputs:
      simulate_deploy:
        type: boolean
        default: true
        required: false

permissions:
  contents: read

jobs:
  simulate_deploy:
    if: ${{ inputs.simulate_deploy }}
    runs-on: ubuntu-latest
    steps:
      - name: Download merged dist artifact from this run
        uses: actions/download-artifact@v4
        with:
          name: all-distributions
          path: dist

      - name: Verify artifacts for deployment
        run: |
          set -euo pipefail
          echo "=== DEPLOYMENT SIMULATION ==="
          echo "Wheels:" && (ls -la dist/*.whl || echo "No wheels found")
          echo "Sdists:" && (ls -la dist/*.tar.gz || echo "No sdists found")

          WHEEL_COUNT=$(ls dist/*.whl 2>/dev/null | wc -l || echo 0)
          SDIST_COUNT=$(ls dist/*.tar.gz 2>/dev/null | wc -l || echo 0)
          echo "Total wheels: $WHEEL_COUNT"
          echo "Total sdists: $SDIST_COUNT"

          for wheel in dist/*.whl 2>/dev/null; do [[ -f "$wheel" ]] && echo "✓ $(basename "$wheel")"; done
          for sdist in dist/*.tar.gz 2>/dev/null; do [[ -f "$sdist" ]] && echo "✓ $(basename "$sdist")"; done

          echo "=== SIMULATION COMPLETE ==="

      - name: Upload deployment simulation results
        uses: actions/upload-artifact@v4
        with:
          name: deployment-simulation-results
          path: dist/
          retention-days: 1
